version: "3.1"

services: 
  mongodb:
    image: "mongo:4.1"
    container_name: mongo
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=mongodb"
    volumes:
      - "./mongodb/data:/data/db"
      # - "/etc/localtime:/etc/localtime"
    ports: 
      - 27017:27017

  mongo-express:
    image: "mongo-express:0.49"
    container_name: "mongo-express"
    restart: "always"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=mongodb"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes: 
  mongodb_data: